# Share.Ninja app — generated by brew/publish_cask.sh in the sharon-apps
# repo (do not edit by hand), published here by its brew/96_tap.sh.
#
# Install:
#   brew tap shareninjahq/sninja
#   brew install --cask share.ninja
cask "share.ninja" do
  version "1.1.4195"
  sha256 "58c0bc817f337a248485f8a7a6c228d7a07d926ade33fea1edf579d046b5f48e"

  url "https://downloads.share.ninja/Share.Ninja-#{version}.zip"
  name "Share.Ninja"
  desc "Share.Ninja secure file sharing app"
  homepage "https://share.ninja"

  # The app updates itself (Tauri updater feed) — `brew upgrade` leaves it
  # alone unless run with --greedy.
  auto_updates true
  depends_on arch: :arm64

  app "Share.Ninja.app"
end
