# Share.Ninja app — generated by brew/publish_cask.sh in the sharon-apps
# repo (do not edit by hand), published here by its brew/96_tap.sh.
#
# Install:
#   brew tap shareninjahq/sninja
#   brew install --cask share.ninja
cask "share.ninja" do
  version "1.1.4688"
  sha256 "b26ad355e9a651018618317a18da2b033dbe2fc90df87f28ebea2427b8da671f"

  url "https://downloads.share.ninja/Share.Ninja-#{version}.zip"
  name "Share.Ninja"
  desc "End-to-end encrypted file sharing: send a link, or send to a device nearby"
  homepage "https://share.ninja"

  # The app updates itself (Tauri updater feed) — `brew upgrade` leaves it
  # alone unless run with --greedy.
  auto_updates true
  depends_on macos: ">= :ventura"
  depends_on arch: :arm64

  app "Share.Ninja.app"
end
