# Share.Ninja desktop app — generated by brew/publish_cask.sh in the
# sharon-apps repo (do not edit by hand), published here by its brew/96_tap.sh.
#
# Install:
#   brew tap shareninjahq/sninja
#   brew install --cask share.ninja
cask "share.ninja" do
  version "1.0.4088"
  sha256 "b394e65e5679a9442d6e8b46b2678142df74d047a75cffb2adb40b5e1fe58df5"

  url "https://downloads.share.ninja/Share.Ninja-#{version}.zip"
  name "Share.Ninja"
  desc "Share.Ninja secure file sharing desktop app"
  homepage "https://share.ninja"

  # The app updates itself (Tauri updater feed) — `brew upgrade` leaves it
  # alone unless run with --greedy.
  auto_updates true
  depends_on arch: :arm64

  app "Share.Ninja.app"
end
