# Share.Ninja CLI — generated by brew/94_package.sh in the sharon-apps repo
# (do not edit by hand), published here by its brew/96_tap.sh.
#
# Install:
#   brew tap shareninjahq/sninja
#   brew install sninja
class Sninja < Formula
  desc "Share.Ninja command line: secure file transfers, and the commander TUI (sninja cmd)"
  homepage "https://share.ninja"
  version "1.1.4306"
  url "https://downloads.share.ninja/sninja/sninja-1.1.4306-aarch64-apple-darwin.tar.gz"
  sha256 "e4399c919bc8e67fd37383000442a4d2383fc0ef0d0752eb3c8accd12915b855"

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "sninja"
  end

  test do
    system bin/"sninja", "--version"
  end
end
