# Share.Ninja CLI — generated by brew/94_package.sh in the sharon-apps repo
# (do not edit by hand), published here by its brew/96_tap.sh.
#
# Install:
#   brew tap shareninjahq/sninja
#   brew install sninja
class Sninja < Formula
  desc "Share.Ninja command line: secure file transfers, and the commander TUI (sninja cmd)"
  homepage "https://share.ninja"
  version "1.1.4272"

  depends_on :macos

  on_macos do
    on_arm do
      url "https://downloads.share.ninja/sninja/sninja-1.1.4272-aarch64-apple-darwin.tar.gz"
      sha256 "954465eb1f67ba60e636cd10620d172baedf673a8de77aa99f8de6eab55013fa"
    end
    on_intel do
      url "https://downloads.share.ninja/sninja/sninja-1.1.4272-x86_64-apple-darwin.tar.gz"
      sha256 "d9670b6fa07a45c89825550bb00d494d72efc9042b2ae16779f39ed089c8252e"
    end
  end

  def install
    bin.install "sninja"
  end

  test do
    system bin/"sninja", "--version"
  end
end
