# Share.Ninja CLI — generated by brew/94_package.sh in the sharon-apps repo
# (do not edit by hand), published here by its brew/96_tap.sh.
#
# Install:
#   brew tap shareninjahq/sninja
#   brew install sninja
class Sninja < Formula
  desc "Share.Ninja command line and two-pane file manager (sninja cmd)"
  homepage "https://share.ninja"
  version "1.1.4688"
  url "https://downloads.share.ninja/sninja/sninja-1.1.4688-aarch64-apple-darwin.tar.gz"
  sha256 "ad78ebf59f40e93fd6a8bdbb6118c8633092203e97ec2d366ec042eb3eef1ad3"

  depends_on macos: :ventura
  depends_on arch: :arm64

  def install
    bin.install "sninja"
  end

  test do
    system bin/"sninja", "--version"
  end
end
